# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8092ce4b576d4deb2ce1050e018fe77b2da62cc5a614eea19d25a3174d77d6df67f0afd8afb57257246dc9560ca50b88ce741c0bcf45587f814f4a261af2b383

test:
  secret_key_base: 95b06b1f9439148e61ac420401192d7106570cce17b4cc851c413de352991eecbfd89091691d58e94e6cfa6ebe37de066b9ae43b702733381af9ccb4acab04ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
